[package]
name = "ruft-examples"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
ruft-client = { path = "../ruft-client" }

log = "0.4.11"
log4rs = "1.0.0"

bytes = "1.0.1"

tokio = { version = "1.4.0", features = ["full"] }

[[example]]
name = "client"
path = "client.rs"
