[package]
name = "ruft-examples"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
ruft-client = { path = "../ruft-client" }

tracing = "0.1"
tracing-subscriber = "0.2"

tokio = { version = "1", features = ["rt"] }

[[example]]
name = "client"
path = "client.rs"
