[package]
name = "ruft-server"
version = "0.0.1"
description = "Ruft Server"
authors = ["Grzegorz Gierlach <gierlachg@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"

derive_more = "0.99.10"

log = "0.4.11"
log4rs = "0.13.0"

async-trait = "0.1.42"

bytes = "0.6.0"

rand = "0.8.0"

futures = "0.3.8"
tokio = { version = "0.3.6", features = ["full"] }
tokio-util = { version = "0.5.1", features = ["full"] }

[dev-dependencies]
mockall = "0.8.3"